### ISSUE TITLE
Adding spm dependency on StencilSwiftKit causes warning in project, soon to be error

### ISSUE THREAD

**Issue by jasonbobier** [SwiftGen/StencilSwiftKit#152]
I'm getting the following warning:

'stencilswiftkit' dependency on 'https://github.com/stencilproject/Stencil.git' conflicts with dependency on 'https://github.com/kylef/Stencil.git' which has the same identity 'stencil'. this will be escalated to an error in future versions of SwiftPM.

My project is required to build without warnings, so this is preventing the use of SwiftGen. Thanks

**Comment by yonaskolb** [comment]
Do you have https://github.com/kylef/Stencil.git listed explicitly in your own dependencies? If so, you can update it to the new org which is https://github.com/stencilproject/Stencil.git

**Comment by djbe** [comment]
As Yonas mentioned, I think you have a dependency on Stencil somewhere else, which is conflicting with the one from SSK. That dependency should be updated to use the new URL for Stencil (has been so for quite a while, ever since it was transferred to a separate organisation).

Closing this as AFAIK it isn't a SSK issue.
