### ISSUE TITLE
Configure Travis

### ISSUE THREAD

**Issue by djbe** [SwiftGen/StencilSwiftKit#3]

**Comment by AliSoftware** [comment]
This will first need #2 as Travis' job will mainly be to run the tests.

I think I'll use Fastlane for this rather than a Rakefile at least for the frameworks like SwiftGenKit.

Rakefile might be more adapted if everything you have to do is mainly shell commands (like transforming the .app into a homebrew-ready dir structure and change the frameworks rpaths) — that's one reason I used a Rakefile for SwiftGen at the beginning — but Fastlane is more adapted for driving Xcode projects like running unit tests and building a framework.

So this issue might as well also concern the creation and configuration of the Fastfile as well as configuring Travis after all.

**Comment by djbe** [comment]
Yeah the issues are in sequence 😄. First the xcode project, then getting the tests to at least work again, etc...
